-- Speech therapy backend: bring the schema up to date.
--
-- GENERATED by scripts/update_database.py --emit-sql, 2026-09-07 10:03 UTC
-- pipeline version at generation: 2.0.0-dev
-- Do not hand-edit: change the SQLAlchemy models and regenerate.
--
-- Idempotent. Every statement is IF NOT EXISTS, so this is safe to
-- run repeatedly, and safe against a database at any earlier version.
--
-- Wrapped in a transaction: if any statement fails, nothing applies.
--
-- NOTE: columns are added NULLABLE even where the model declares them
-- NOT NULL. A NOT NULL column cannot be added to a table that already
-- has rows without deciding what those rows should contain, and that
-- decision does not belong in a generated script. Existing rows will
-- read NULL, which is the honest value -- a row written by the old
-- text pipeline genuinely has no verdict or confidence.

BEGIN;

-- ======================================================================
-- Tables
-- ======================================================================
CREATE TABLE IF NOT EXISTS activity_categories (
	id UUID NOT NULL, 
	name VARCHAR(50) NOT NULL, 
	description VARCHAR(200), 
	type VARCHAR(50), 
	difficulty_level VARCHAR(20), 
	PRIMARY KEY (id), 
	UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS caregivers (
	id UUID NOT NULL, 
	username VARCHAR(50) NOT NULL, 
	email VARCHAR(100) NOT NULL, 
	hashed_password VARCHAR(200) NOT NULL, 
	is_active BOOLEAN, 
	PRIMARY KEY (id), 
	UNIQUE (username), 
	UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS token_blacklist (
	id SERIAL NOT NULL, 
	token VARCHAR, 
	blacklisted_on TIMESTAMP WITHOUT TIME ZONE, 
	expires_at TIMESTAMP WITHOUT TIME ZONE, 
	PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS activity_items (
	id UUID NOT NULL, 
	name VARCHAR(300) NOT NULL, 
	description VARCHAR(300), 
	category_id UUID, 
	image_url VARCHAR(300), 
	audio_url VARCHAR(300), 
	difficulty_level VARCHAR(20), 
	PRIMARY KEY (id), 
	FOREIGN KEY(category_id) REFERENCES activity_categories (id)
);

CREATE TABLE IF NOT EXISTS children (
	id UUID NOT NULL, 
	caregiver_id UUID, 
	name VARCHAR(100) NOT NULL, 
	age INTEGER, 
	diagnosis_date DATE, 
	notes TEXT, 
	therapy_goals TEXT, 
	created_at DATE, 
	PRIMARY KEY (id), 
	FOREIGN KEY(caregiver_id) REFERENCES caregivers (id)
);

CREATE TABLE IF NOT EXISTS child_category_association (
	child_id UUID, 
	category_id UUID, 
	FOREIGN KEY(child_id) REFERENCES children (id), 
	FOREIGN KEY(category_id) REFERENCES activity_categories (id)
);

CREATE TABLE IF NOT EXISTS child_performance (
	id UUID NOT NULL, 
	child_id UUID NOT NULL, 
	category_id UUID, 
	overall_score FLOAT, 
	verbal_attempts INTEGER, 
	verbal_success INTEGER, 
	selection_attempts INTEGER, 
	selection_success INTEGER, 
	last_updated TIMESTAMP WITHOUT TIME ZONE, 
	PRIMARY KEY (id), 
	FOREIGN KEY(child_id) REFERENCES children (id), 
	FOREIGN KEY(category_id) REFERENCES activity_categories (id)
);

CREATE TABLE IF NOT EXISTS learning_paths (
	id UUID NOT NULL, 
	child_id UUID NOT NULL, 
	category_id UUID NOT NULL, 
	target_score FLOAT, 
	current_priority INTEGER, 
	status VARCHAR(20), 
	started_at TIMESTAMP WITHOUT TIME ZONE, 
	mastered_at TIMESTAMP WITHOUT TIME ZONE, 
	created_at TIMESTAMP WITHOUT TIME ZONE, 
	updated_at TIMESTAMP WITHOUT TIME ZONE, 
	PRIMARY KEY (id), 
	FOREIGN KEY(child_id) REFERENCES children (id), 
	FOREIGN KEY(category_id) REFERENCES activity_categories (id)
);

CREATE TABLE IF NOT EXISTS study_assignments (
	id UUID NOT NULL, 
	child_id UUID NOT NULL, 
	group_index INTEGER NOT NULL, 
	block1_condition VARCHAR(1) NOT NULL, 
	block1_list VARCHAR(1) NOT NULL, 
	block2_condition VARCHAR(1) NOT NULL, 
	block2_list VARCHAR(1) NOT NULL, 
	excluded BOOLEAN NOT NULL, 
	exclusion_reason VARCHAR(300), 
	assigned_at TIMESTAMP WITHOUT TIME ZONE, 
	PRIMARY KEY (id), 
	UNIQUE (child_id), 
	FOREIGN KEY(child_id) REFERENCES children (id)
);

CREATE TABLE IF NOT EXISTS therapy_sessions (
	id UUID NOT NULL, 
	child_id UUID, 
	caregiver_id UUID, 
	category_id UUID, 
	start_time TIMESTAMP WITHOUT TIME ZONE, 
	end_time TIMESTAMP WITHOUT TIME ZONE, 
	current_level VARCHAR(20), 
	condition VARCHAR(1), 
	is_completed BOOLEAN, 
	PRIMARY KEY (id), 
	FOREIGN KEY(child_id) REFERENCES children (id), 
	FOREIGN KEY(caregiver_id) REFERENCES caregivers (id), 
	FOREIGN KEY(category_id) REFERENCES activity_categories (id)
);

CREATE TABLE IF NOT EXISTS caregiver_feedback (
	id UUID NOT NULL, 
	session_id UUID, 
	child_id UUID, 
	caregiver_id UUID, 
	rating INTEGER, 
	comments TEXT, 
	progress_achievements TEXT, 
	areas_for_improvement TEXT, 
	behavioral_observations TEXT, 
	created_at TIMESTAMP WITHOUT TIME ZONE, 
	feedback_type VARCHAR(20), 
	PRIMARY KEY (id), 
	FOREIGN KEY(session_id) REFERENCES therapy_sessions (id), 
	FOREIGN KEY(child_id) REFERENCES children (id), 
	FOREIGN KEY(caregiver_id) REFERENCES caregivers (id)
);

CREATE TABLE IF NOT EXISTS gaze_tracking_data (
	id UUID NOT NULL, 
	session_id UUID NOT NULL, 
	child_id UUID NOT NULL, 
	session_duration_ms BIGINT NOT NULL, 
	total_attention_time_ms BIGINT NOT NULL, 
	attention_percentage FLOAT NOT NULL, 
	time_in_zone1_ms BIGINT NOT NULL, 
	time_in_zone2_ms BIGINT NOT NULL, 
	time_in_zone3_ms BIGINT NOT NULL, 
	zone1_percentage FLOAT NOT NULL, 
	zone2_percentage FLOAT NOT NULL, 
	zone3_percentage FLOAT NOT NULL, 
	average_pleasure FLOAT NOT NULL, 
	average_excitement FLOAT NOT NULL, 
	engagement_percentage FLOAT NOT NULL, 
	smile_percentage FLOAT NOT NULL, 
	total_gaze_data_points INTEGER NOT NULL, 
	session_start_time BIGINT NOT NULL, 
	session_end_time BIGINT NOT NULL, 
	created_at TIMESTAMP WITHOUT TIME ZONE, 
	PRIMARY KEY (id), 
	FOREIGN KEY(session_id) REFERENCES therapy_sessions (id), 
	FOREIGN KEY(child_id) REFERENCES children (id)
);

CREATE TABLE IF NOT EXISTS session_activities (
	id UUID NOT NULL, 
	session_id UUID, 
	item_id UUID, 
	attempt_number INTEGER, 
	is_correct BOOLEAN, 
	response_type VARCHAR(10), 
	response_text VARCHAR, 
	feedback VARCHAR, 
	pronunciation_score FLOAT, 
	response_time_seconds FLOAT, 
	error_type VARCHAR(300), 
	substitutions JSON, 
	repetition_count INTEGER, 
	stammering_detected BOOLEAN, 
	word_analysis JSON, 
	correct_word_count INTEGER, 
	total_word_count INTEGER, 
	condition VARCHAR(1), 
	verdict VARCHAR(20), 
	verdict_score FLOAT, 
	confidence FLOAT, 
	gated BOOLEAN, 
	expected_phones JSON, 
	observed_phones JSON, 
	phone_scores JSON, 
	diagnoses JSON, 
	applied_folds JSON, 
	stress_error BOOLEAN, 
	named_phone VARCHAR(4), 
	feedback_word_count INTEGER, 
	audio_ref VARCHAR, 
	pipeline_version VARCHAR(20), 
	config_hash VARCHAR(16), 
	model_id VARCHAR(120), 
	stage_timings_ms JSON, 
	created_at TIMESTAMP WITHOUT TIME ZONE, 
	PRIMARY KEY (id), 
	FOREIGN KEY(session_id) REFERENCES therapy_sessions (id), 
	FOREIGN KEY(item_id) REFERENCES activity_items (id)
);

-- ======================================================================
-- Columns (no-ops where the column already exists)
-- ======================================================================
-- activity_categories
ALTER TABLE "activity_categories" ADD COLUMN IF NOT EXISTS "name" VARCHAR(50);
ALTER TABLE "activity_categories" ADD COLUMN IF NOT EXISTS "description" VARCHAR(200);
ALTER TABLE "activity_categories" ADD COLUMN IF NOT EXISTS "type" VARCHAR(50);
ALTER TABLE "activity_categories" ADD COLUMN IF NOT EXISTS "difficulty_level" VARCHAR(20);

-- caregivers
ALTER TABLE "caregivers" ADD COLUMN IF NOT EXISTS "username" VARCHAR(50);
ALTER TABLE "caregivers" ADD COLUMN IF NOT EXISTS "email" VARCHAR(100);
ALTER TABLE "caregivers" ADD COLUMN IF NOT EXISTS "hashed_password" VARCHAR(200);
ALTER TABLE "caregivers" ADD COLUMN IF NOT EXISTS "is_active" BOOLEAN;

-- token_blacklist
ALTER TABLE "token_blacklist" ADD COLUMN IF NOT EXISTS "token" VARCHAR;
ALTER TABLE "token_blacklist" ADD COLUMN IF NOT EXISTS "blacklisted_on" TIMESTAMP WITHOUT TIME ZONE;
ALTER TABLE "token_blacklist" ADD COLUMN IF NOT EXISTS "expires_at" TIMESTAMP WITHOUT TIME ZONE;

-- activity_items
ALTER TABLE "activity_items" ADD COLUMN IF NOT EXISTS "name" VARCHAR(300);
ALTER TABLE "activity_items" ADD COLUMN IF NOT EXISTS "description" VARCHAR(300);
ALTER TABLE "activity_items" ADD COLUMN IF NOT EXISTS "category_id" UUID;
ALTER TABLE "activity_items" ADD COLUMN IF NOT EXISTS "image_url" VARCHAR(300);
ALTER TABLE "activity_items" ADD COLUMN IF NOT EXISTS "audio_url" VARCHAR(300);
ALTER TABLE "activity_items" ADD COLUMN IF NOT EXISTS "difficulty_level" VARCHAR(20);

-- children
ALTER TABLE "children" ADD COLUMN IF NOT EXISTS "caregiver_id" UUID;
ALTER TABLE "children" ADD COLUMN IF NOT EXISTS "name" VARCHAR(100);
ALTER TABLE "children" ADD COLUMN IF NOT EXISTS "age" INTEGER;
ALTER TABLE "children" ADD COLUMN IF NOT EXISTS "diagnosis_date" DATE;
ALTER TABLE "children" ADD COLUMN IF NOT EXISTS "notes" TEXT;
ALTER TABLE "children" ADD COLUMN IF NOT EXISTS "therapy_goals" TEXT;
ALTER TABLE "children" ADD COLUMN IF NOT EXISTS "created_at" DATE;

-- child_category_association
ALTER TABLE "child_category_association" ADD COLUMN IF NOT EXISTS "child_id" UUID;
ALTER TABLE "child_category_association" ADD COLUMN IF NOT EXISTS "category_id" UUID;

-- child_performance
ALTER TABLE "child_performance" ADD COLUMN IF NOT EXISTS "child_id" UUID;
ALTER TABLE "child_performance" ADD COLUMN IF NOT EXISTS "category_id" UUID;
ALTER TABLE "child_performance" ADD COLUMN IF NOT EXISTS "overall_score" FLOAT;
ALTER TABLE "child_performance" ADD COLUMN IF NOT EXISTS "verbal_attempts" INTEGER;
ALTER TABLE "child_performance" ADD COLUMN IF NOT EXISTS "verbal_success" INTEGER;
ALTER TABLE "child_performance" ADD COLUMN IF NOT EXISTS "selection_attempts" INTEGER;
ALTER TABLE "child_performance" ADD COLUMN IF NOT EXISTS "selection_success" INTEGER;
ALTER TABLE "child_performance" ADD COLUMN IF NOT EXISTS "last_updated" TIMESTAMP WITHOUT TIME ZONE;

-- learning_paths
ALTER TABLE "learning_paths" ADD COLUMN IF NOT EXISTS "child_id" UUID;
ALTER TABLE "learning_paths" ADD COLUMN IF NOT EXISTS "category_id" UUID;
ALTER TABLE "learning_paths" ADD COLUMN IF NOT EXISTS "target_score" FLOAT;
ALTER TABLE "learning_paths" ADD COLUMN IF NOT EXISTS "current_priority" INTEGER;
ALTER TABLE "learning_paths" ADD COLUMN IF NOT EXISTS "status" VARCHAR(20);
ALTER TABLE "learning_paths" ADD COLUMN IF NOT EXISTS "started_at" TIMESTAMP WITHOUT TIME ZONE;
ALTER TABLE "learning_paths" ADD COLUMN IF NOT EXISTS "mastered_at" TIMESTAMP WITHOUT TIME ZONE;
ALTER TABLE "learning_paths" ADD COLUMN IF NOT EXISTS "created_at" TIMESTAMP WITHOUT TIME ZONE;
ALTER TABLE "learning_paths" ADD COLUMN IF NOT EXISTS "updated_at" TIMESTAMP WITHOUT TIME ZONE;

-- study_assignments
ALTER TABLE "study_assignments" ADD COLUMN IF NOT EXISTS "child_id" UUID;
ALTER TABLE "study_assignments" ADD COLUMN IF NOT EXISTS "group_index" INTEGER;
ALTER TABLE "study_assignments" ADD COLUMN IF NOT EXISTS "block1_condition" VARCHAR(1);
ALTER TABLE "study_assignments" ADD COLUMN IF NOT EXISTS "block1_list" VARCHAR(1);
ALTER TABLE "study_assignments" ADD COLUMN IF NOT EXISTS "block2_condition" VARCHAR(1);
ALTER TABLE "study_assignments" ADD COLUMN IF NOT EXISTS "block2_list" VARCHAR(1);
ALTER TABLE "study_assignments" ADD COLUMN IF NOT EXISTS "excluded" BOOLEAN;
ALTER TABLE "study_assignments" ADD COLUMN IF NOT EXISTS "exclusion_reason" VARCHAR(300);
ALTER TABLE "study_assignments" ADD COLUMN IF NOT EXISTS "assigned_at" TIMESTAMP WITHOUT TIME ZONE;

-- therapy_sessions
ALTER TABLE "therapy_sessions" ADD COLUMN IF NOT EXISTS "child_id" UUID;
ALTER TABLE "therapy_sessions" ADD COLUMN IF NOT EXISTS "caregiver_id" UUID;
ALTER TABLE "therapy_sessions" ADD COLUMN IF NOT EXISTS "category_id" UUID;
ALTER TABLE "therapy_sessions" ADD COLUMN IF NOT EXISTS "start_time" TIMESTAMP WITHOUT TIME ZONE;
ALTER TABLE "therapy_sessions" ADD COLUMN IF NOT EXISTS "end_time" TIMESTAMP WITHOUT TIME ZONE;
ALTER TABLE "therapy_sessions" ADD COLUMN IF NOT EXISTS "current_level" VARCHAR(20);
ALTER TABLE "therapy_sessions" ADD COLUMN IF NOT EXISTS "condition" VARCHAR(1);
ALTER TABLE "therapy_sessions" ADD COLUMN IF NOT EXISTS "is_completed" BOOLEAN;

-- caregiver_feedback
ALTER TABLE "caregiver_feedback" ADD COLUMN IF NOT EXISTS "session_id" UUID;
ALTER TABLE "caregiver_feedback" ADD COLUMN IF NOT EXISTS "child_id" UUID;
ALTER TABLE "caregiver_feedback" ADD COLUMN IF NOT EXISTS "caregiver_id" UUID;
ALTER TABLE "caregiver_feedback" ADD COLUMN IF NOT EXISTS "rating" INTEGER;
ALTER TABLE "caregiver_feedback" ADD COLUMN IF NOT EXISTS "comments" TEXT;
ALTER TABLE "caregiver_feedback" ADD COLUMN IF NOT EXISTS "progress_achievements" TEXT;
ALTER TABLE "caregiver_feedback" ADD COLUMN IF NOT EXISTS "areas_for_improvement" TEXT;
ALTER TABLE "caregiver_feedback" ADD COLUMN IF NOT EXISTS "behavioral_observations" TEXT;
ALTER TABLE "caregiver_feedback" ADD COLUMN IF NOT EXISTS "created_at" TIMESTAMP WITHOUT TIME ZONE;
ALTER TABLE "caregiver_feedback" ADD COLUMN IF NOT EXISTS "feedback_type" VARCHAR(20);

-- gaze_tracking_data
ALTER TABLE "gaze_tracking_data" ADD COLUMN IF NOT EXISTS "session_id" UUID;
ALTER TABLE "gaze_tracking_data" ADD COLUMN IF NOT EXISTS "child_id" UUID;
ALTER TABLE "gaze_tracking_data" ADD COLUMN IF NOT EXISTS "session_duration_ms" BIGINT;
ALTER TABLE "gaze_tracking_data" ADD COLUMN IF NOT EXISTS "total_attention_time_ms" BIGINT;
ALTER TABLE "gaze_tracking_data" ADD COLUMN IF NOT EXISTS "attention_percentage" FLOAT;
ALTER TABLE "gaze_tracking_data" ADD COLUMN IF NOT EXISTS "time_in_zone1_ms" BIGINT;
ALTER TABLE "gaze_tracking_data" ADD COLUMN IF NOT EXISTS "time_in_zone2_ms" BIGINT;
ALTER TABLE "gaze_tracking_data" ADD COLUMN IF NOT EXISTS "time_in_zone3_ms" BIGINT;
ALTER TABLE "gaze_tracking_data" ADD COLUMN IF NOT EXISTS "zone1_percentage" FLOAT;
ALTER TABLE "gaze_tracking_data" ADD COLUMN IF NOT EXISTS "zone2_percentage" FLOAT;
ALTER TABLE "gaze_tracking_data" ADD COLUMN IF NOT EXISTS "zone3_percentage" FLOAT;
ALTER TABLE "gaze_tracking_data" ADD COLUMN IF NOT EXISTS "average_pleasure" FLOAT;
ALTER TABLE "gaze_tracking_data" ADD COLUMN IF NOT EXISTS "average_excitement" FLOAT;
ALTER TABLE "gaze_tracking_data" ADD COLUMN IF NOT EXISTS "engagement_percentage" FLOAT;
ALTER TABLE "gaze_tracking_data" ADD COLUMN IF NOT EXISTS "smile_percentage" FLOAT;
ALTER TABLE "gaze_tracking_data" ADD COLUMN IF NOT EXISTS "total_gaze_data_points" INTEGER;
ALTER TABLE "gaze_tracking_data" ADD COLUMN IF NOT EXISTS "session_start_time" BIGINT;
ALTER TABLE "gaze_tracking_data" ADD COLUMN IF NOT EXISTS "session_end_time" BIGINT;
ALTER TABLE "gaze_tracking_data" ADD COLUMN IF NOT EXISTS "created_at" TIMESTAMP WITHOUT TIME ZONE;

-- session_activities
ALTER TABLE "session_activities" ADD COLUMN IF NOT EXISTS "session_id" UUID;
ALTER TABLE "session_activities" ADD COLUMN IF NOT EXISTS "item_id" UUID;
ALTER TABLE "session_activities" ADD COLUMN IF NOT EXISTS "attempt_number" INTEGER;
ALTER TABLE "session_activities" ADD COLUMN IF NOT EXISTS "is_correct" BOOLEAN;
ALTER TABLE "session_activities" ADD COLUMN IF NOT EXISTS "response_type" VARCHAR(10);
ALTER TABLE "session_activities" ADD COLUMN IF NOT EXISTS "response_text" VARCHAR;
ALTER TABLE "session_activities" ADD COLUMN IF NOT EXISTS "feedback" VARCHAR;
ALTER TABLE "session_activities" ADD COLUMN IF NOT EXISTS "pronunciation_score" FLOAT;
ALTER TABLE "session_activities" ADD COLUMN IF NOT EXISTS "response_time_seconds" FLOAT;
ALTER TABLE "session_activities" ADD COLUMN IF NOT EXISTS "error_type" VARCHAR(300);
ALTER TABLE "session_activities" ADD COLUMN IF NOT EXISTS "substitutions" JSON;
ALTER TABLE "session_activities" ADD COLUMN IF NOT EXISTS "repetition_count" INTEGER;
ALTER TABLE "session_activities" ADD COLUMN IF NOT EXISTS "stammering_detected" BOOLEAN;
ALTER TABLE "session_activities" ADD COLUMN IF NOT EXISTS "word_analysis" JSON;
ALTER TABLE "session_activities" ADD COLUMN IF NOT EXISTS "correct_word_count" INTEGER;
ALTER TABLE "session_activities" ADD COLUMN IF NOT EXISTS "total_word_count" INTEGER;
ALTER TABLE "session_activities" ADD COLUMN IF NOT EXISTS "condition" VARCHAR(1);
ALTER TABLE "session_activities" ADD COLUMN IF NOT EXISTS "verdict" VARCHAR(20);
ALTER TABLE "session_activities" ADD COLUMN IF NOT EXISTS "verdict_score" FLOAT;
ALTER TABLE "session_activities" ADD COLUMN IF NOT EXISTS "confidence" FLOAT;
ALTER TABLE "session_activities" ADD COLUMN IF NOT EXISTS "gated" BOOLEAN;
ALTER TABLE "session_activities" ADD COLUMN IF NOT EXISTS "expected_phones" JSON;
ALTER TABLE "session_activities" ADD COLUMN IF NOT EXISTS "observed_phones" JSON;
ALTER TABLE "session_activities" ADD COLUMN IF NOT EXISTS "phone_scores" JSON;
ALTER TABLE "session_activities" ADD COLUMN IF NOT EXISTS "diagnoses" JSON;
ALTER TABLE "session_activities" ADD COLUMN IF NOT EXISTS "applied_folds" JSON;
ALTER TABLE "session_activities" ADD COLUMN IF NOT EXISTS "stress_error" BOOLEAN;
ALTER TABLE "session_activities" ADD COLUMN IF NOT EXISTS "named_phone" VARCHAR(4);
ALTER TABLE "session_activities" ADD COLUMN IF NOT EXISTS "feedback_word_count" INTEGER;
ALTER TABLE "session_activities" ADD COLUMN IF NOT EXISTS "audio_ref" VARCHAR;
ALTER TABLE "session_activities" ADD COLUMN IF NOT EXISTS "pipeline_version" VARCHAR(20);
ALTER TABLE "session_activities" ADD COLUMN IF NOT EXISTS "config_hash" VARCHAR(16);
ALTER TABLE "session_activities" ADD COLUMN IF NOT EXISTS "model_id" VARCHAR(120);
ALTER TABLE "session_activities" ADD COLUMN IF NOT EXISTS "stage_timings_ms" JSON;
ALTER TABLE "session_activities" ADD COLUMN IF NOT EXISTS "created_at" TIMESTAMP WITHOUT TIME ZONE;

COMMIT;

-- ======================================================================
-- Verification: returns ZERO rows when the schema is complete.
-- Any row is a table.column the models declare but the database lacks.
-- ======================================================================
SELECT e.table_name, e.column_name
FROM (VALUES
    ('activity_categories', 'id'),
    ('activity_categories', 'name'),
    ('activity_categories', 'description'),
    ('activity_categories', 'type'),
    ('activity_categories', 'difficulty_level'),
    ('caregivers', 'id'),
    ('caregivers', 'username'),
    ('caregivers', 'email'),
    ('caregivers', 'hashed_password'),
    ('caregivers', 'is_active'),
    ('token_blacklist', 'id'),
    ('token_blacklist', 'token'),
    ('token_blacklist', 'blacklisted_on'),
    ('token_blacklist', 'expires_at'),
    ('activity_items', 'id'),
    ('activity_items', 'name'),
    ('activity_items', 'description'),
    ('activity_items', 'category_id'),
    ('activity_items', 'image_url'),
    ('activity_items', 'audio_url'),
    ('activity_items', 'difficulty_level'),
    ('children', 'id'),
    ('children', 'caregiver_id'),
    ('children', 'name'),
    ('children', 'age'),
    ('children', 'diagnosis_date'),
    ('children', 'notes'),
    ('children', 'therapy_goals'),
    ('children', 'created_at'),
    ('child_category_association', 'child_id'),
    ('child_category_association', 'category_id'),
    ('child_performance', 'id'),
    ('child_performance', 'child_id'),
    ('child_performance', 'category_id'),
    ('child_performance', 'overall_score'),
    ('child_performance', 'verbal_attempts'),
    ('child_performance', 'verbal_success'),
    ('child_performance', 'selection_attempts'),
    ('child_performance', 'selection_success'),
    ('child_performance', 'last_updated'),
    ('learning_paths', 'id'),
    ('learning_paths', 'child_id'),
    ('learning_paths', 'category_id'),
    ('learning_paths', 'target_score'),
    ('learning_paths', 'current_priority'),
    ('learning_paths', 'status'),
    ('learning_paths', 'started_at'),
    ('learning_paths', 'mastered_at'),
    ('learning_paths', 'created_at'),
    ('learning_paths', 'updated_at'),
    ('study_assignments', 'id'),
    ('study_assignments', 'child_id'),
    ('study_assignments', 'group_index'),
    ('study_assignments', 'block1_condition'),
    ('study_assignments', 'block1_list'),
    ('study_assignments', 'block2_condition'),
    ('study_assignments', 'block2_list'),
    ('study_assignments', 'excluded'),
    ('study_assignments', 'exclusion_reason'),
    ('study_assignments', 'assigned_at'),
    ('therapy_sessions', 'id'),
    ('therapy_sessions', 'child_id'),
    ('therapy_sessions', 'caregiver_id'),
    ('therapy_sessions', 'category_id'),
    ('therapy_sessions', 'start_time'),
    ('therapy_sessions', 'end_time'),
    ('therapy_sessions', 'current_level'),
    ('therapy_sessions', 'condition'),
    ('therapy_sessions', 'is_completed'),
    ('caregiver_feedback', 'id'),
    ('caregiver_feedback', 'session_id'),
    ('caregiver_feedback', 'child_id'),
    ('caregiver_feedback', 'caregiver_id'),
    ('caregiver_feedback', 'rating'),
    ('caregiver_feedback', 'comments'),
    ('caregiver_feedback', 'progress_achievements'),
    ('caregiver_feedback', 'areas_for_improvement'),
    ('caregiver_feedback', 'behavioral_observations'),
    ('caregiver_feedback', 'created_at'),
    ('caregiver_feedback', 'feedback_type'),
    ('gaze_tracking_data', 'id'),
    ('gaze_tracking_data', 'session_id'),
    ('gaze_tracking_data', 'child_id'),
    ('gaze_tracking_data', 'session_duration_ms'),
    ('gaze_tracking_data', 'total_attention_time_ms'),
    ('gaze_tracking_data', 'attention_percentage'),
    ('gaze_tracking_data', 'time_in_zone1_ms'),
    ('gaze_tracking_data', 'time_in_zone2_ms'),
    ('gaze_tracking_data', 'time_in_zone3_ms'),
    ('gaze_tracking_data', 'zone1_percentage'),
    ('gaze_tracking_data', 'zone2_percentage'),
    ('gaze_tracking_data', 'zone3_percentage'),
    ('gaze_tracking_data', 'average_pleasure'),
    ('gaze_tracking_data', 'average_excitement'),
    ('gaze_tracking_data', 'engagement_percentage'),
    ('gaze_tracking_data', 'smile_percentage'),
    ('gaze_tracking_data', 'total_gaze_data_points'),
    ('gaze_tracking_data', 'session_start_time'),
    ('gaze_tracking_data', 'session_end_time'),
    ('gaze_tracking_data', 'created_at'),
    ('session_activities', 'id'),
    ('session_activities', 'session_id'),
    ('session_activities', 'item_id'),
    ('session_activities', 'attempt_number'),
    ('session_activities', 'is_correct'),
    ('session_activities', 'response_type'),
    ('session_activities', 'response_text'),
    ('session_activities', 'feedback'),
    ('session_activities', 'pronunciation_score'),
    ('session_activities', 'response_time_seconds'),
    ('session_activities', 'error_type'),
    ('session_activities', 'substitutions'),
    ('session_activities', 'repetition_count'),
    ('session_activities', 'stammering_detected'),
    ('session_activities', 'word_analysis'),
    ('session_activities', 'correct_word_count'),
    ('session_activities', 'total_word_count'),
    ('session_activities', 'condition'),
    ('session_activities', 'verdict'),
    ('session_activities', 'verdict_score'),
    ('session_activities', 'confidence'),
    ('session_activities', 'gated'),
    ('session_activities', 'expected_phones'),
    ('session_activities', 'observed_phones'),
    ('session_activities', 'phone_scores'),
    ('session_activities', 'diagnoses'),
    ('session_activities', 'applied_folds'),
    ('session_activities', 'stress_error'),
    ('session_activities', 'named_phone'),
    ('session_activities', 'feedback_word_count'),
    ('session_activities', 'audio_ref'),
    ('session_activities', 'pipeline_version'),
    ('session_activities', 'config_hash'),
    ('session_activities', 'model_id'),
    ('session_activities', 'stage_timings_ms'),
    ('session_activities', 'created_at')
) AS e(table_name, column_name)
LEFT JOIN information_schema.columns c
       ON c.table_schema = current_schema()
      AND c.table_name  = e.table_name
      AND c.column_name = e.column_name
WHERE c.column_name IS NULL
ORDER BY e.table_name, e.column_name;
